#@data/values
---
git_uri: git@github.com:GaloyMoney/faq.blink.sv.git
git_branch: main
github_private_key: ((github.private_key))

openai_api_key: ((pinecone-sync.openai_api_key))
pinecone_api_key: ((pinecone-sync.pinecone_api_key))
airtable_access_token: ((pinecone-sync.airtable_access_token))
github_token: ((github.api_token))
